### ISSUE TITLE
[Homework 6] Question about From trait

### ISSUE THREAD

**Issue by znunc** [kaist-cp/cs220#124]
I implemented the From trait of Polynomial assuming that the input parameter is among (u64,i64,f64).
I ignored the case when the input parameter is Polynomial.
However, somehow the code worked fine.

I found out that following code works fine, showing the same result.
```
    let s:Polynomial<u64> = Polynomial::from(Polynomial::from(from_usize::<u64>(2)));
    let t:Polynomial<u64> = Polynomial::from(from_usize::<u64>(2));

    println!("{:?}",s.coefficients);
    println!("{:?}",t.coefficients);
```

It seems like rust compiler consider _Type_::from(_a_) equal to a if the type of _a_ is same as the _Type_
Why is it happening?

**Comment by minseongg** [comment]
It is because `From` trait is reflexive, which means that `From<T> for T` is implemented. ([Reference](https://doc.rust-lang.org/std/convert/trait.From.html#generic-implementations))

**Comment by znunc** [comment]
```
impl<T> const From<T> for T {
    /// Returns the argument unchanged.
    fn from(t: T) -> T {
        t
    }
}
```

So it is implemented as above.

Is there any other way for us to check if the trait is reflexive or not? (other than looking at the doc)

**Comment by minseongg** [comment]
I think one possible way can be using Rust's supertrait.

For example, below code can be compiled because `From<T>` is implemented for any type `T`. ([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=b5b1b475faef7497e35b31a5e8e4ae6e))

```rust
trait IsReflexive<T>: From<T> {}

impl<T> IsReflexive<T> for T {}
```

However, below code is not can be compiled because `Add<T>` is not implemented for any type `T`. ([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=43a95b1b1b5ba126e3837bbdb50cb494))

```rust
use std::ops::Add;

trait IsReflexive<T>: Add<T> {}

impl<T> IsReflexive<T> for T {}
```
