### ISSUE TITLE
Returning type that implements a specific trait

### ISSUE THREAD

**Issue by choejms** [kaist-cp/cs220#133]
When we are returning a type that implements a specific trait, we can use impl Syntax like below according to the Rust book.

```
fn returns_summarizable() -> impl Summary {
    Tweet {
        username: String::from("horse_ebooks"),
        content: String::from(
            "of course, as you probably already know, people",
        ),
        reply: false,
        retweet: false,
    }
}
```

But can we also write the same function without using the impl syntax?
For example, can we do something like 

```
fn returns_summarizable<T>() -> T: Summary {
    Tweet {
        username: String::from("horse_ebooks"),
        content: String::from(
            "of course, as you probably already know, people",
        ),
        reply: false,
        retweet: false,
    }
}
```

I tried the function above in Rust Playground but I am getting the following error message.

```
error: expected one of `!`, `(`, `+`, `::`, `<`, `where`, or `{`, found `:`
  --> src/main.rs:48:34
   |
48 | fn returns_summarizable<T>() -> T: Summary {
   |                                  ^ expected one of 7 possible tokens

error: could not compile `playground` due to previous error
```

Is the syntax above not supported by Rust?

**Comment by Lee-Janggun** [comment]
Yes, that particular syntax is not supported. Also even if it did, the syntax you have written suggests a return type of `T` satisfying the trait bound `Summary`. However then, the compiler cannot infer that `Tweet` is of type `T`, so compilation will fail.

**Comment by minseongg** [comment]
+) Maybe you wanted to write code like this: [Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=bde0138f538e701295942b4d22340093)

```rust
fn returns_summarizable<T: Summary>() -> T {
    Tweet {
        username: String::from("horse_ebooks"),
        content: String::from(
            "of course, as you probably already know, people",
        ),
        reply: false,
        retweet: false,
    }
}
```

However, it also fails to compile because the return type of `returns_summarizable` can be any type which implements `Summary` trait. For example, you can call `returns_summarizable<NewsArticle>()` where `NewsArticle` is another struct which implements `Summary` trait. But the body of `returns_summarizable` always returns `Tweet`.

```
error[[E0308]](https://doc.rust-lang.org/stable/error-index.html#E0308): mismatched types
  --> src/lib.rs:11:5
   |
10 |   fn returns_summarizable<T: Summary>() -> T {
   |                           -                -
   |                           |                |
   |                           |                expected `T` because of return type
   |                           |                help: consider using an impl return type: `impl Summary`
   |                           this type parameter
11 | /     Tweet {
12 | |         username: String::from("horse_ebooks"),
13 | |         content: String::from(
14 | |             "of course, as you probably already know, people",
...  |
17 | |         retweet: false,
18 | |     }
   | |_____^ expected type parameter `T`, found struct `Tweet`
   |
   = note: expected type parameter `T`
                      found struct `Tweet`

For more information about this error, try `rustc --explain E0308`.
error: could not compile `playground` due to previous error
```

**Comment by m-spitfire** [comment]
> But can we also write the same function without using the impl syntax?

If you want to same function without using the impl syntax, you would have to specify the trait in the [Generic parameters](https://doc.rust-lang.org/reference/items/generics.html):
```rust
fn returns_summarizable<T: Summary>() -> T {
    Tweet {
        username: String::from("horse_ebooks"),
        content: String::from(
            "of course, as you probably already know, people",
        ),
        reply: false,
        retweet: false,
    }
}
```
But there's a difference between above and the impl syntax. See [this](https://doc.rust-lang.org/reference/types/impl-trait.html#differences-between-generics-and-impl-trait-in-return-position) for the explanation.
If you want to know why you can't use such syntax, that is because in [function](https://doc.rust-lang.org/reference/items/functions.html) declaration the _FunctionReturnType_ have to be a [Type expression](https://doc.rust-lang.org/reference/types.html#type-expressions), and the trait type expressions are [trait objects](https://doc.rust-lang.org/reference/types/trait-object.html) and [impl trait](https://doc.rust-lang.org/reference/types/impl-trait.html)

**Comment by choejms** [comment]
Thank you for the detailed explanations. Appreciate it!
