### ISSUE TITLE
[HW8] using items in vector of `funny_map` function

### ISSUE THREAD

**Issue by yumincho** [kaist-cp/cs220#147]
Hi! I have a question about homework8.

I keep trying to use items in vector `vs` for `repeat` function, but I get some errors.

Is there any way I can use those items without `Copy` trait? I found that it worked when I added trait bound of `Copy` to T(`T: Copy`). I doubt whether there is another solution or not..

Thank you!

**Comment by minseongg** [comment]
You cannot get the exact data of the collection (which has type `T`) by using the `iter` method because it borrows each element of the collection through each iteration. One way to resolve this is using `into_iter` instead of `iter`; it consumes the collection so that it will provide the exact data on each iteration.

For more details on the difference between `iter` and `into_iter`, please refer to this: https://doc.rust-lang.org/rust-by-example/flow_control/for.html#for-and-iterators

**Comment by yumincho** [comment]
That's perfectly what I needed. Thanks a lot for your help even at late night! :D
