### ISSUE TITLE
[Question hw7]About next for FindIter and collect's inner implementation

### ISSUE THREAD

**Issue by dripcharacter** [kaist-cp/cs220#170]
Hello, since hw7 is over, I made some question about hw7.
In class, I asked a question about hw7 to professor that
'It was relatively easy to understand since there weren't many abstraction in earlier class codes, but we have many abstracted codes in class and homework and these make me hard to understand.'
After that question I talked with professor about I couldn't understand why we implement next function since I couldn't find usage of next function in hw7 and hw7_grade.
Now I think that next function is used in collect like ' find("abc".as_bytes(), "abcdabcd".as_bytes()).collect::<Vec<usize>>()' since almost every function in iter uses next internally.
These are my questions.
1. Does my understanding of next is right?
2. If it is right, I want to know the inner implementation of iter::collect(). I searched source code of 'doc.rust-lang.org', but I just got the fact that iter::collect uses 'FromIterator::from_iter' and 'FromIterator::from_iter' just return original collection. Does next() is used when programmer implement FromIterator::from_iter for their own data type? if it is right, I want to know why FindIter worked well though we didn't implement from_iter function.

**Comment by choejms** [comment]
1. We implement `next()` because `FindIter` implements `Iterator` trait and `next` is a required method in Iterator trait. 
2. Here is the source code for `collect()`.

```
    fn collect<B: FromIterator<Self::Item>>(self) -> B
    where
        Self: Sized,
    {
        FromIterator::from_iter(self)
    }
```
As you said, for `FromIterator::from_iter`, we have 
`fn from_iter<T: IntoIterator<Item = A>>(iter: T) -> Self;`.

Since we are calling `(Some FindIter struct we created).collect::<Vec<usize>>()`, we are effectively saying `B` is `<Vec<usize>>`. So Rust can infer that the type of `Self` in `FromIterator::from_iter` is `<Vec<usize>>`
Therefore, `Vec::from_iter(some FindIter struct we created)` is called.

This is the source code for Vec::from_iter().
```
impl<T> FromIterator<T> for Vec<T> {
    #[inline]
    fn from_iter<I: IntoIterator<Item = T>>(iter: I) -> Vec<T> {
        <Self as SpecFromIter<T, I::IntoIter>>::from_iter(iter.into_iter())
    }
}
```
In SpecFromIter::from_iter, we have the following source code.
```
impl<T, I> SpecFromIter<T, I> for Vec<T>
where
    I: Iterator<Item = T>,
{
    default fn from_iter(iterator: I) -> Self {
       SpecFromIterNested::from_iter(iterator)
    }
}

```
And inside the `SpecFromIterNested::from_iter`, we use `next()`.
```
impl<T, I> SpecFromIterNested<T, I> for Vec<T>
where
    I: Iterator<Item = T>,
{
    default fn from_iter(mut iterator: I) -> Self {
        let mut vector = match iterator.next() {
            None => return Vec::new() ...
```

So our implementation of `next()` is indeed used when we call `collect()`.

**Comment by dripcharacter** [comment]
Thank you for your kind reply. I got some points!
