### ISSUE TITLE
[Homework 9 and 10] Can we define helper functions?

### ISSUE THREAD

**Issue by AlijonovMukhammaddiyor** [kaist-cp/cs220#175]

**Comment by minseongg** [comment]
Yes, you can.

**Comment by Re-st** [comment]
Hello. I have one question about this issue.

As I defined helper functions, 

error: missing documentation for a function
   --> src/assignments/assignment10.rs:#######:1
    |
157 | ############################ {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
note: the lint level is defined here
   --> src/lib.rs:26:9
    |
26  | #![deny(missing_docs)]
    |         ^^^^^^^^^^^^

error: could not compile `cs220` due to previous error


pops up. If I silence #![deny(missing_docs)] in lib.rs       , theh code passes. But when I upload on gg, the error pops up. Checked the log to find out that 'missing documentation for a function' was the problem.

How can I solve this?

**Comment by zzz845zz** [comment]
I closed this issue because the timeline of hw9 and hw10 is passed. Please make a new issue if you have a question.
