### ISSUE TITLE
Question about closure.

### ISSUE THREAD

**Issue by vm3fk5dla2** [kaist-cp/cs220#189]
Dear Professor and TAs.

I have a question about closure.

As it says in the Rustbook, 
"One interesting aspect here is that we’ve passed a closure that calls self.most_stocked() on the current Inventory instance. The standard library didn’t need to know anything about the Inventory or ShirtColor types we defined, or the logic we want to use in this scenario. The closure captures an immutable reference to the self Inventory instance and passes it with the code we specify to the unwrap_or_else method. Functions, on the other hand, are not able to capture their environment in this way."

This explains the difference between the closure and the function when solving the problem of giving shirts. But I can't understand
the meaning of "capture". Isn't it possible to capture similar to that in a function? I want to watch an example..

**Comment by buttercrab** [comment]
Let's see two code snippets.

```rust
fn main() {
    let a = 1;
    
    (|| {
        println!("{}", a);
    })();
}
```
[link to tio.run](https://tio.run/##KyotLvn/Py1PITcxM09DU6GaSwEIclJLFBIVbBUMrcFcMKFRUwOVBYGCosy8kpw8RQ2l6lolHYVETYjKWk0NIKv2/38A)

```rust
fn main() {
    let a = 1;
    
    fn inner() {
        println!("{}", a);
    }
}
```
[link to tio.run](https://tio.run/##KyotLvn/Py1PITcxM09DU6GaSwEIclJLFBIVbBUMrcFcMAFUk5mXl1oEVwQCBUWZeSU5eYoaStW1SjoKiZoQDbVctf//AwA)

(I attached tio.run link since rust playground is not working while I'm writing this)

You can see the error message from second code snippet.
The difference between closure and function is that closure can "capture" variables from outside the closure whereas function cannot "capture" variables from outside.

Since rust have ownership system, the value used in closure is either by reference or moved.

See two code snippets below.

```rust
fn main() {
	let a = String::from("hello");

	(|| {
		println!("{}", a);
	})();

	println!("{}", a);
}
```
[link to tio.run](https://tio.run/##KyotLvn/Py1PITcxM09DU6GaizMntUQhUcFWIbikKDMv3coqrSg/V0MpIzUnJ19J05qLi1OjpgakjrMAKF@Sk6eooVRdq6SjkAiU5KzV1ACrwSJX@/8/AA)

```rust
fn main() {
	let a = String::from("hello");

	(move || {
		println!("{}", a);
	})();

	println!("{}", a);
}
```
[link to tio.run](https://tio.run/##bcq7DYAgEADQGqY4qY7ECTRO4QQUoCR8DKINMPuJ1tbvpevMRCaAVzaghMKZ0xkULLDmZMM2TSZFj2LXzkUhZ84Z@nhrqPXN7OgpuzCgKE2MoPpgTeIXf6wRPQ)

Since the value is moved in second code snippet, there comes the error that we cannot use `a` after.

**Comment by jeehoonkang** [comment]
@buttercrab Thank you for a great answer! Closing, but feel free to reopen this issue.
