### ISSUE TITLE
Why does rust not allow some generic parameter or variable to clone()?

### ISSUE THREAD

**Issue by 7dy109** [kaist-cp/cs220#219]
Why does rust not allow some generic parameter or variable to clone()?
Why does rust restrict "clonable" things?
(we should type "where T : Clone" to clone some generic parameter)

I have no idea about the reason to deny cloning some generic parameter which is not clone trait.

**Comment by Lee-Janggun** [comment]
Because there are types that cannot be cloned. Most notably, there is the mutable reference type (`&mut T`) where only one must exist.

Additionally, what you are representing may not make sense as a cloneable object. For instance if you had a type representing a ownership for a CPU core, such type is not cloneable as you can't clone a CPU core at runtime.

**Comment by 7dy109** [comment]
Thank you for your nice answer!
