### ISSUE TITLE
Plagiarism policy and LLMs

### ISSUE THREAD

**Issue by osutaiko** [kaist-cp/cs220#275]
I was wondering why we are allowed to use LLMs such as ChatGPT, while the course policy strictly forbids plagiarism in any manner. Does this policy mean that we are not supposed to directly use code generated by LLMs, but rather use them only for understanding high-level concepts?

**Comment by jirheee** [comment]
No, you can use the code generated from LLMs like ChatGPT, github copilot, and etc. We adopt this policy because we believe LLMs will be an essential tool for programmers, and students should learn how to use them properly. Therefore, we will not regard using code generated from LLM as plagiarism, and recommend cooperating with the LLM while doing your assignments.

**Comment by AnHaechan** [comment]
I think @osutaiko has a fair point, because some argues LLMs "use other's works without a proper mention".

But at least for this course, we recommend using LLMs because...
* As it will be (and already is?) the new norm of programming.
* At least, you're not copy-pasting other student's code. Using LLMs requires certain level of problem solving.

**Comment by osutaiko** [comment]
Thank you for the clarification, I'll use LLMs wisely for my studying!
