### ISSUE TITLE
[Assignment 8] Is there a representative solution code for the "exp" function?

### ISSUE THREAD

**Issue by 1starJ** [kaist-cp/cs220#337]
### Googling Result

https://en.wikipedia.org/wiki/Church_encoding

### ChatGPT Result

None

### Your question here

Hello, It's just a curiosity-based question, but is there any solution code for the `exp` function?
I ask this question because I could not write a code that is based on the comment, and I wrote a code using `mult`.
The comment for the `exp` function says that "to output n to the power of m, apply the Church numeral of m to the Church numeral of n" and I understand the theory but cannot embody it. It seems that I cannot just apply `m` to `n` because the type does not match. But I think there is some way to embody it.
Please let me know if I can get the solution, or if I can't, please give me some hints.

**Comment by jirheee** [comment]
Unfortunately, we cannot show you the solution to the problem.

And the comment is enough to solve the problem. Actually, I do not understand why you cannot apply m to n because of the type since `Church<T>` is a generic type for `T`, which means it can be applied to any type that has this form: `Rc<dyn Fn(T) -> T>`

**Comment by 1starJ** [comment]
Thank you so much for your hint.
