### ISSUE TITLE
About integer overflow in assignment02, fn choose

### ISSUE THREAD

**Issue by ShinDongHeon** [kaist-cp/cs220#375]
### Related Issue

d

### Googling Result

d

### ChatGPT Result

d

### Your question here

Comments says to neglect integer overflow, so i did
When grading by ./scripts/grade.sh 02 by git bash, i found that overflow actually occurs and testcase failed with
The other cases was correct except for 67 when i checked by myself.
will i get deducted in this case?

**Comment by kingdoctor123** [comment]
Yes. You will be deducted if your solution did not get full score on gg. 

In fact, `We assume the absence of integer overflow.` means that we will not specify what you should do in case of overflow since a correct solution will run without such a problem. So please fix your code so that your solution no longer suffers from the problem of overflow.

**Comment by ShinDongHeon** [comment]
Thanks
