### ISSUE TITLE
[Assignment 1] ./scripts/submit.sh이 실행이 안됩니다.

### ISSUE THREAD

**Issue by zzupi06** [kaist-cp/cs220#381]
### Related Issue

https://github.com/kaist-cp/cs220/issues/363

### Googling Result

https://www.tecmint.com/install-zip-and-unzip-in-linux/

### ChatGPT Result

https://chatgpt.com/share/66fed9a6-87c0-8005-8cdc-4ef7383112f9

### Your question here

안녕하세요, cs220 수업을 수강하고 있는 20240619 임준영 입니다.
./scripts/submit.sh을 git base에 입력하면 
$ ./scripts/submit.sh
C:/Program Files/Git/usr/bin/zip.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory

이런 식으로 오류가 발생합니다. 이런 오류 때문에 target directory에도 assignment zip 파일이 생성되지 않아 과제를 제출할 수 없었습니다. assignment 1 코드를 작성한 후 /scripts/grade.sh 1를 실행하여 통과한 것을 확인하고, zip파일을 수동으로 만들어서 gg에 제출도 해봤지만 정답이라고 뜨지 않습니다. 컴퓨터를 재부팅 해보고 Git Bash를 삭제 후 재설치 했는데도 문제가 해결되지 않습니다. 이런 경우에 어떻게 과제를 제출할 수 있을까요? 과제 제출 기한 전에 이 문제를 해결하지 못할 것 같아 대안(ex. assignment 파일을 메일로 조교님께 보내드리기 등)을 통해 과제를 제출 할 수 있도록 도와주신다면 대단히 감사드리겠습니다.

**Comment by Jaewookim08** [comment]
Hello,  
All the scripts are designed to run on a Linux machine, so they might not work as expected on Windows.

The error occurs because the code couldn't find a zip executable. Here are a few possible solutions:

- **(Recommended):** Move your code (possibly using Git) to our development server and run `submit.sh` there.
- Creating the zip file manually should also work. Make sure the files in the zip are not inside a folder.
- I don't recommend this, but you could install the `zip.exe` executable for Windows and try again.
