### ISSUE TITLE
[Assignment 5] What should I return when I cannot find target value in binary search?

### ISSUE THREAD

**Issue by 20240769** [kaist-cp/cs220#388]
### Googling Result

Cannot found

### ChatGPT Result

https://chatgpt.com/c/6704f243-5868-8001-ab99-3b359c52483e

### Your question here

What should I return when I cannot find target value in binary search? Since I can't modify the line above I can't return -1 nor make exception. Does the test case suppose that there always exists target value v in array int a?

**Comment by Jaewookim08** [comment]
The `requires` and `ensures` clauses together define the function's specification—what the function should return for a given input. If you understand the specification in the template code, you'll know what the function is expected to return in both cases: whether the array contains a value or not.

Additionally, there are no 'test cases' in Assignment 5 because Why3 verifies whether the assertions hold true for all possible inputs. You might want to look into 'program verification.'

**Comment by 20240769** [comment]
thankyou
