### ISSUE TITLE
code-server compile error

### ISSUE THREAD

**Issue by easter1000** [kaist-cp/cs220#404]
I tried using the remote server's code-server for the first time while preparing for the test environment. (I usually used vs code desktop).
I installed cargo and rustc using sudo apt install, but cargo doc --open, ./scripts/grade.sh do not work.
Since I could not access github in the seb environment, I used my own browser to connect github. I also did git pull, but it still did not work.
I think this problem is caused by cs220/src/lib.rs not being compiled. How do I solve it?
![Inline-image-2024-10-16 18 03 28 259](https://github.com/user-attachments/assets/1255f555-0be9-4096-910c-2eb2a4f97b33)

**Comment by Jaewookim08** [comment]
I think you have installed cargo and rustc directly using apt. We recommend using rustup to install those, since rustup automatically provides the required rust toolchains (versions). Please restart the workspace (which will remove the current cargo and rustc), and try again after installing rustup through apt.

By the way, the development server provided for the exam is not cloud.fearless.com. To test the exam environment, please follow the instructions in the rehearsal_part2.seb file

**Comment by yujin51** [comment]
I have a sampe problem as above, so I tried removing cargo and rustc and install rustup by using apt. The problem that ./scripts/grade.sh do not work has been remained. How can I solve it?
