### ISSUE TITLE
[Assignment 11] Can it be done in safe mode?

### ISSUE THREAD

**Issue by ssamt** [kaist-cp/cs220#435]
### Googling Result

https://doc.rust-lang.org/src/alloc/collections/linked_list.rs.html

### ChatGPT Result

N/A

### Your question here

I found linked list implementation very difficult, so I tried to consult the official LinkedList library in Rust. But it seems like they use unsafe codes everywhere... Can this assignment be done in safe Rust only? If it can be, why is the official implementation using so much unsafe?

**Comment by Jaewookim08** [comment]
- Yes, all the assignments are solvable using only safe Rust.
- Our linked list is singly linked list, i.e., a node hold only the reference to the next node. The ownership handling is easy, since we can just set each node to be owned by the previous node.
- The linked list in std is doubly linked list, i.e., a node hold references of both the next and previous nodes. This makes the ownership handling tricky. A node cannot be owned by the previous node, because it can also be referenced by the next node.
  - Therefore, the std linked list intentionally give up handling the node's ownership using the Rust type system. This is why it uses unsafe blocks. Instead, the library guarantees safety through safe API (It is library maintainer's responsibility to make sure that the API is really safe). Even though the inner code is not protected by the ownership system, the users of the list API will be able to use the list as if the list holds ownership of all the nodes.
   - Another approach could be using reference counting (`Rc`) and locks (`Mutex`). This would allow to implement doubly linked list using only safe Rust, but it would imply significant overhead.
