### ISSUE TITLE
[Homework 3] I have a few questions considering my_map function

### ISSUE THREAD

**Issue by malore350** [kaist-cp/cs220#47]
Such a long function of input/ouputs got me confused.

1. Am I supposed to solve this problem by checking the input type, f.e. (if TypeId::of::<T>() == TypeId::of::<String>() ...)?
2. When I call MySome, it requires input. Is the input of this function **T**? When I use it, it doesn't accept it.

Would really appreciate if anyone explains how this function works, cannot really use what we learned on it (enum).

**Comment by m-spitfire** [comment]
Hello! You shouldn't think about types since our custom `Option` type `MyOption` is [generic](https://doc.rust-lang.org/book/ch10-01-syntax.html) over the type `T`(`T` is not a function it's a generic type). This function is our equivalent function of standard library's `Option::map` function. The equivalent [example from docs](https://doc.rust-lang.org/stable/std/option/enum.Option.html#examples-11) would be:
```rust
let maybe_some_string = MySome(String::from("Hello, World!"));
let maybe_some_len = my_map(maybe_some_string, |s| s.len());

assert_eq!(maybe_some_len, MySome(13));
```
More on generics:
* https://doc.rust-lang.org/reference/items/generics.html

**Comment by malore350** [comment]
> Hello! You shouldn't think about types since our custom `Option` type `MyOption` is [generic](https://doc.rust-lang.org/book/ch10-01-syntax.html) over the type `T`(`T` is not a function it's a generic type). This function is our equivalent function of standard library's `Option::map` function. The equivalent [example from docs](https://doc.rust-lang.org/stable/std/option/enum.Option.html#examples-11) would be:
> 
> ```rust
> let maybe_some_string = MySome(String::from("Hello, World!"));
> let maybe_some_len = my_map(maybe_some_string, |s| s.len());
> 
> assert_eq!(maybe_some_len, MySome(13));
> ```
> 
> More on generics:
> 
> * https://doc.rust-lang.org/reference/items/generics.html

Thank you, this really helped to understand and solve it.

**Comment by minseongg** [comment]
@m-spitfire Thanks, we updated the descriptions. https://github.com/kaist-cp/cs220/commit/ae41c7d61ba55c33814f1865849893d1be66010d
