### ISSUE TITLE
How can I throw away unused result? 

### ISSUE THREAD

**Issue by quanxi1** [kaist-cp/cs220#59]
Sometimes I see 'unused result of type T' error, for the cases like using remove or pop just to remove an element, but not to use it elsewhere. 
I guess it's because the lint doesn't allow to leave any result unused but what should I do if I don't need the result but can't find any other method that do what I want while making no result?

**Comment by quanxi1** [comment]
@leejy12 Thanks!

**Comment by Lee-Janggun** [comment]
If the return type is an `bool` or `Option<T>`, or an `Result<O,E>` and you are sure what kind of return value is, an even better option will be to use `assert!` with `Option::is_some()`, `Result::is_err()` etc for debugging.

**Comment by koosaga** [comment]
I don't think it is a good idea. Why does the linter forces me to do this?

**Comment by m-spitfire** [comment]
> I don't think it is a good idea. Why does the linter force me to do this?

I am guessing you're asking why linter forces you to ignore the `Result`? If so, the linter doesn't force you to ignore the `Result`, it's the exact opposite, it forces you to use the `Result` so that you handle the error case. Ignoring it is your choice. Read more on [Results must be used](https://doc.rust-lang.org/std/result/index.html#results-must-be-used).

**Comment by koosaga** [comment]
The linter forces to use the result (`let _ = func();`), I'm asking why I can't ignore it (`func();`). Is it constrained by language?

**Comment by m-spitfire** [comment]
> The linter forces to use the result (`let _ = func();`), I'm asking why I can't ignore it (`func();`). Is it constrained by language?

As I said, linter doesn't force you to use that pattern, it's your choice that you use that pattern. Instead, you can do something like 
```rust
if func().is_err() {
    panic!("func() has failed")
}
```
as the TA said or using many other methods of `Result`. Please consult the documentation.

Coming to your last question, yes it is constrained by the language the the `cs220` crate. The `Result` enum is declared with `#[must_use]` attribute(see the link in my previous reply). So by default, the compiler gives you a warning that you're not using the `Result` here if you do `func();`. But in the `cs220` crate has a macro called [`#![deny(warnings)]`](https://doc.rust-lang.org/rustc/lints/groups.html) in its top-level file, [`lib.rs`](https://github.com/kaist-cp/cs220/blob/main/src/lib.rs#L23) . This makes all the warnings compiler produces errors and doesn't allow the program to compile with warnings.

**Comment by koosaga** [comment]
> But in the cs220 crate has a macro called [#![deny(warnings)]](https://doc.rust-lang.org/rustc/lints/groups.html) in its top-level file, [lib.rs](https://github.com/kaist-cp/cs220/blob/main/src/lib.rs#L23)

I see. That feels pretty pedantic to me but I can understand the rationale behind the macro. Thank you for the detailed reply!

**Comment by Lee-Janggun** [comment]
The purpose of denying warning is to make one write more idiomatic code.

Especially in the case of `Result` types, one of the most common bugs made while using them is ignoring the error variant, when in reality there should be separate error handling. The `#[must_use]` macro prevents such problems. 

In general, linters shipped with the language (not limited to Rust are designed well enough so that for the majority, following it will lead to better code. Of course, this may require you to write seemingly weird code such as `let _ = func();`, but overall it should increase the quality an productivity of your program.
