### ISSUE TITLE
[Homework 3] Iterating HashMap in for loop

### ISSUE THREAD

**Issue by intellkim** [kaist-cp/cs220#60]
When iterating HashMap in for loop, should I add & in front of HashMap's name? I am confused about it.

**Comment by minseongg** [comment]
Short answer: If you want to reuse the hashmap after the loop, then you should use `&` in front of the name of hashmap.

---

If you do not use `&` in front of the name of hashmap, it is consumed in `for` loop so that the exact data is provided on each iteration. Once the hashmap has been consumed, it is no longer available for reuse as it has "moved" within the loop.

Example: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=4d6a086a191ae27d74f12b2e748f4da9

```rust
use std::collections::HashMap;

fn main() {
    let mut m = HashMap::<usize, usize>::new();
    m.insert(1, 3);
    m.insert(2, 4);

    for (k, v) in m { // type of `k` and `v` is `usize`
        println!("key: {}, value: {}", k, v);
    }

    // `m` is consumed and we cannot reuse after the loop. If you comment out the below line, then it fails to compile.
    // println!("{:?}", m);
}
```

If you use `&` in front of the name of hashmap, then each element of the hashmap is borrowed through each iteration of the loop. Thus leaving the hashmap untouched and available for reuse after the loop.

Example: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=9103655e24522b48c8165ecc4738a853

```rust
use std::collections::HashMap;

fn main() {
    let mut m = HashMap::<usize, usize>::new();
    m.insert(1, 3);
    m.insert(2, 4);

    for (k, v) in &m { // type of `k` and `v` is `&usize`
        println!("key: {}, value: {}", k, v);
    }

    println!("{:?}", m); // `m` is untouched and we can reuse after the loop.
}
```

For more details, please refer to this:

- [`for` and iterators](https://doc.rust-lang.org/rust-by-example/flow_control/for.html#for-and-iterators) (By default, `for` loop will apply the `into_iter` function to the collection)
- [`into_iter` for `&HashMap`, `&mut HashMap`, `HashMap`](https://doc.rust-lang.org/stable/std/collections/struct.HashMap.html#impl-IntoIterator-for-%26%27a%20HashMap%3CK%2C%20V%2C%20S%3E)

**Comment by intellkim** [comment]
thank you.

**Comment by intellkim** [comment]
what is difference between adding & and using clone method?

**Comment by zzz845zz** [comment]
`&(reference)` does not copy(make a new one) the data but `clone()` does.

For this example, 

```rust
let s1 = String::from("hello");
let s2 = s1.clone();
let s = &s; 
```

`s2` will be shown in memory as Figure 4-3 in [Rust book section 4.1](https://doc.rust-lang.org/book/ch04-01-what-is-ownership.html) and `s` will be shown as Figure 4-5 in [section 4.2](https://doc.rust-lang.org/book/ch04-02-references-and-borrowing.html).
