### ISSUE TITLE
Invariant condition in Euclidean Division Code

### ISSUE THREAD

**Issue by blziiiin** [kaist-cp/cs220#86]
I was wondering that _invariant { a = b * q + r }_ is enough, but I need to add _0 <= r_ to get prove.
I though that _require { 0<=a }_ and _while r>=b_ implicitly ensures that r is larger or equal to zero. Why should I add _0 <= r_?
1) Does not while loop condition ensure that r is larger than b or r-b cannot be less than zero?
2) If 1)is true, how program ensures _exists r: int. a = b * result + r /\ 0 <= r < b_ even though I didn't add _r < b_ to invariant?

**Comment by choejms** [comment]
1. The solver alone is not able to deduce all steps for verification, so the programmer must add "0 <= r" as a hint to the solver. You are right in saying that {0 <= a} and {r >= b} ensures {r >= 0}, but the solver cannot deduce it alone, and I think this is a limitation of Why3.
2. The solver can deduce r < b because when the while loop stops, r must be less than b. 

Usually, the solver can deduce statements that can be directly inferred from invariants. Also, the solver knows that if a loop is terminated, then the condition of the loop is no longer true. 
But the solver has difficulty making deductions from assignments (e.g. Using  r = a, 0 <= a, r>=b r <- r - b to deduce that r >= 0). In that case, we must add the invariants.

**Comment by jeehoonkang** [comment]
I totally agree with @choejms .
